service: serverless-rule-engine

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  - serverless-plugin-typescript
  - serverless-esbuild
  - serverless-offline

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node16
    platform: node
    concurrency: 10
    exclude: "[*]"

functions:
  rule_engine:
    handler: src/rule-engine.rule_engine
    events:
      # Invoke Lambda function every minute
      - schedule: cron(*/5 * * * * *)
