[profile.default]
src = "./packages/contracts/src"
test = "./packages/contracts/test"
libs = ["./packages/contracts/lib"]
out = "./packages/contracts/out"
cache_path = "./packages/contracts/cache"
verbosity = 1
remappings = [
  "forge-std/=./packages/contracts/lib/forge-std/src/"
]